import * as FS from 'fs';
import * as OS from 'os';
import * as Path from 'path';

import {logger} from '@makeflow/makescript-agent';
import {Castable, Command, Options, command, metadata, option} from 'clime';
import prompts from 'prompts';
import {Tiva} from 'tiva';
import {v4 as uuidv4} from 'uuid';

import {JSONConfigFile} from '../config';
import {main} from '../main';

const WORKSPACE_PATH_DEFAULT = Path.resolve(
  OS.homedir(),
  '.config',
  'makescript',
);
const GENERATE_CONFIG_DEFAULT = false;

const CONFIG_FILE_NAME = 'makescript.json';

export class CLIOptions extends Options {
  @option({
    flag: 'g',
    description: 'Whether only to generate makescript config file.',
    toggle: true,
    default: GENERATE_CONFIG_DEFAULT,
  })
  generateConfigOnly!: boolean;

  @option({
    flag: 'w',
    description: 'The path for makescript to work.',
    default: WORKSPACE_PATH_DEFAULT,
  })
  workspace!: Castable.Directory;
}

@command()
export default class extends Command {
  @metadata
  async execute({generateConfigOnly, workspace}: CLIOptions): Promise<void> {
    let configFilePath = Path.join(workspace.fullName, CONFIG_FILE_NAME);

    let configFileExists = FS.existsSync(configFilePath);

    if (configFileExists && generateConfigOnly) {
      console.warn(
        `The config file "${configFilePath}" has existed, so the new config has not generated.`,
      );
      return;
    }

    if (!configFileExists) {
      let dirname = workspace.fullName;

      let {withDefaultAgent} = await prompts({
        type: 'confirm',
        name: 'withDefaultAgent',
        message: 'Do you want run with a default agent?',
        initial: true,
      });

      // There is a bug (or unhandled behavior) with 'prompts'.
      // When user press CTRL + C , program will continue to execute with empty answers.
      // https://github.com/terkelg/prompts/issues/252
      if (withDefaultAgent === undefined) {
        process.exit(0);
      }

      let defaultAgentScriptsRepoURL: string | undefined;

      if (withDefaultAgent) {
        let {repoURL} = await prompts({
          type: 'text',
          name: 'repoURL',
          message: 'Please enter the git url of the scripts repo',
          validate: value => /^(https?:\/\/.+)|(\w+\.git)$/.test(value),
        });

        // There is a bug (or unhandled behavior) with 'prompts'.
        // When user press CTRL + C , program will continue to execute with empty answers.
        // https://github.com/terkelg/prompts/issues/252
        if (!repoURL) {
          process.exit(0);
        }

        defaultAgentScriptsRepoURL = repoURL;
      }

      let jsonConfig: JSONConfigFile = {
        host: 'localhost',
        port: 8900,
        url: `http://localhost:8900`,

        makeflow: {
          baseURL: 'https://makeflow.com',
          powerApp: {
            name: 'makescript',
            displayName: 'MakeScript',
            description: 'Auto generated by makescript',
          },
        },

        defaultAgent:
          withDefaultAgent && defaultAgentScriptsRepoURL
            ? {scriptsRepoURL: defaultAgentScriptsRepoURL}
            : undefined,

        joinToken: uuidv4(),

        resourcesPath: Path.join(OS.tmpdir(), 'makescript-resources'),
      };

      let jsonConfigText = JSON.stringify(jsonConfig);

      if (!FS.existsSync(dirname)) {
        FS.mkdirSync(dirname, {recursive: true});
      }

      FS.writeFileSync(configFilePath, jsonConfigText);
    }

    if (generateConfigOnly) {
      return;
    }

    let jsonConfigText = FS.readFileSync(configFilePath).toString();

    let jsonConfig: JSONConfigFile = JSON.parse(jsonConfigText);

    let tiva = new Tiva({
      project: Path.join(__dirname, '../../../src/program'),
    });

    logger.info('Checking config file ...');

    try {
      await tiva.validate(
        {module: './config', type: 'JSONConfigFile'},
        jsonConfig,
      );

      await main(tiva, {
        ...jsonConfig,
        workspace: workspace.fullName,
      });
    } catch (error) {
      if (error.diagnostics) {
        logger.error(
          `Config file structure does not match:\n${error.diagnostics}`,
        );
      } else {
        logger.error(`Unknown error occurred:\n${error.message}`);
      }

      process.exit(1);
    }
  }
}
